const constants = {
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  COUNT_FAVORITE: "COUNT_FAVORITE",
  FETCH_FAVORITE: "FETCH_FAVORITE",
  FETCH_ARTISTS: "FETCH_ARTISTS",
  FETCH_ALBUMS: "FETCH_ALBUMS",
  FETCH_ALBUM_DETAIL: "FETCH_ALBUM_DETAIL",
  START_FETCHING: "START_FETCHING",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
};


export default constants;
