const constants = {
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  COUNT_FAVORITES: "COUNT_FAVORITES",
  FETCH_FAVORITES: "FETCH_FAVORITES",
  FETCH_FAVORITE: "FETCH_FAVORITE",
  FETCH_ARTISTS: "FETCH_ARTISTS",
  FETCH_ALBUMS: "FETCH_ALBUMS",
  FETCH_ALBUM_DETAIL: "FETCH_ALBUM_DETAIL",
  START_FETCHING: "START_FETCHING",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  ADD_MESSAGE: "ADD_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
  FETCH_MESSAGE: "FETCH_MESSAGE",
  ADD_SEARCH_TERM: "ADD_SEARCH_TERM",
  FETCH_SEARCH_TERM: "FETCH_SEARCH_TERM",
  CLEAR_SEARCH_TERM: "CLEAR_SEARCH_TERM",
};


export default constants;
